version: 2.0

jobs:
  deploy:
    docker:
      - image: circleci/node:11.14
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm i
      - run:
          name: deploy to Firebase Hosting
          command: npm run deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
