name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install, build
      run: |
        npm install
        npm run generate
    - name: deploy to Firebase Hosting
      run: |
        ./node_modules/.bin/firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
